import { readFileSync, statSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { SOUND_MANIFEST } from './manifest';

const REQUIRED_SOUNDS = [
  'parlour.card.draw.stock',
  'parlour.card.draw.discard',
  'parlour.card.discard.flight',
  'parlour.card.land',
  'parlour.card.flip',
  'parlour.deal.card',
  'parlour.stock.shuffle',
  'parlour.turn.ready',
  'parlour.clock.tick',
  'parlour.time.up',
  'parlour.ui.press',
  'parlour.room.player-joined',
  'parlour.room.player-left',
  'parlour.match.win',
  'parlour.match.lose',
  'blitz.knock',
  'blitz.fanfare',
  'blitz.life.loss',
  'wildpile.wild.surge',
  'wildpile.reverse',
  'wildpile.skip',
  'wildpile.draw-stack',
  'wildpile.color',
  'wildpile.caught',
  'wildpile.voice.reverse',
  'wildpile.voice.skip',
  'wildpile.voice.draw-two',
  'wildpile.voice.draw-four',
  'wildpile.voice.stacked',
  'wildpile.voice.wild',
  'wildpile.voice.red',
  'wildpile.voice.yellow',
  'wildpile.voice.green',
  'wildpile.voice.blue',
  'wildpile.voice.last-card',
  'hearts.pass-commit',
  'hearts.trick-sweep',
  'hearts.point-heart',
  'hearts.queen-drop',
  'hearts.hearts-broken',
  'hearts.moon-shoot',
  'euchre.order-up',
  'euchre.trump-called',
  'euchre.pass',
  'euchre.alone',
  'euchre.dealer-pickup',
  'euchre.trick-collect',
  'euchre.euchre-sting',
  'euchre.march-fanfare',
  'euchre.score-chime',
  'spades.bid',
  'spades.bid-nil',
  'spades.bids-complete',
  'spades.trick-collect',
  'spades.spades-broken',
  'spades.nil-made',
  'spades.nil-failed',
  'spades.set',
  'spades.contract-made',
  'spades.bag-penalty',
  'spades.score-chime',
  'poker.chips-soft',
  'poker.chips-hard',
  'poker.fold',
  'poker.check',
  'poker.board',
  'poker.pot',
  'poker.award',
  'poker.bust',
  'poker.blinds-up',
  // Oh Hell reuses the trick-taking samples rather than shipping a fourth
  // near-identical set; the ids are still declared so each one is checked to
  // point at a real, non-empty MP3.
  'ohhell.trump',
  'ohhell.bid',
  'ohhell.bids-complete',
  'ohhell.trick-collect',
  'ohhell.score',
  'ohhell.match-score',
  // Spite reuses the shared card samples; the ids are still declared so each
  // is checked to point at a real, non-empty MP3.
  'spite.wild',
  'spite.complete',
  'spite.win',
  'spite.discard',
  'spite.draw',
  'scopa.capture',
  'scopa.pose',
  'scopa.scopa',
  'scopa.sweep',
  'scopa.score',
  'golf.draw',
  'golf.move',
  'golf.hole-out',
  'golf.win',
  'klondike.draw',
  'klondike.recycle',
  'klondike.move',
  'klondike.flip',
  'klondike.foundation',
  'klondike.win',
  'gin.knock',
  'gin.gin',
  'gin.big-gin',
  'gin.undercut',
  'cribbage.peg-move',
  'cribbage.score-run',
  'cribbage.score-pair',
  'cribbage.score-fifteen',
  'cribbage.thirtyone',
  'cribbage.go-knock',
  'cribbage.heels',
  'cribbage.crib-slide',
  'cribbage.show-reveal',
  'cribbage.skunk',
  'ratscrew.slap-win',
  'ratscrew.mislap',
  'ratscrew.window-open',
  'ratscrew.challenge',
  'ratscrew.scoop',
  'ratscrew.burn',
  'ratscrew.comeback',
  'president.set-slam',
  'president.pass',
  'president.pile-clear',
  'president.crown',
  'president.scum',
  'president.role-chime',
  'president.exchange-swish',
  'eights.wild',
  'eights.suit',
  'eights.skip',
  'eights.reverse',
  'eights.draw-stack',
  'eights.out',
  'eights.blocked',
  'eights.score',
  'freecell.move',
  'freecell.park',
  'freecell.foundation',
  'freecell.win',
  'spider.deal',
  'spider.move',
  'spider.flip',
  'spider.suit-clear',
  'spider.win',
  'pyramid.draw',
  'pyramid.recycle',
  'pyramid.pair',
  'pyramid.king',
  'pyramid.hole-out',
  'pyramid.win',
  'tripeaks.flip',
  'tripeaks.move',
  'tripeaks.recycle',
  'tripeaks.hole-out',
  'tripeaks.win',
  'durak.beat',
  'durak.pickup',
  'durak.transfer',
  'palace.burn',
  'palace.flip-down',
  'palace.pickup',
  'palace.out',
  'pinochle.bid',
  'pinochle.pass',
  'pinochle.trump',
  'pinochle.meld',
  'pinochle.trick-collect',
  'pinochle.contract-made',
  'pinochle.set',
  'pinochle.score-chime',
] as const;

describe('production audio suite', () => {
  it('ships every required sound as a locally synthesized WAV', () => {
    const byId = new Map(SOUND_MANIFEST.map((sound) => [sound.id, sound]));

    for (const id of REQUIRED_SOUNDS) {
      const sound = byId.get(id);
      expect(sound, `${id} is declared`).toBeDefined();
      const path = join(process.cwd(), 'public', sound!.src);
      expect(statSync(path).size, `${id} is not an empty placeholder`).toBeGreaterThan(1_000);
      const header = readFileSync(path).subarray(0, 12);
      expect(header.subarray(0, 4).toString()).toBe('RIFF');
      expect(header.subarray(8, 12).toString()).toBe('WAVE');
      expect(sound!.src).toMatch(/^\/audio\/original\/[^/]+\.wav$/);
    }

    expect(SOUND_MANIFEST.map((sound) => sound.id)).toEqual(REQUIRED_SOUNDS);
  });

  it('reserves every manifest slot for SFX; music lives in the music manifest', () => {
    for (const sound of SOUND_MANIFEST) {
      expect(sound.channel).toBe('sfx');
    }
    expect(SOUND_MANIFEST.some((sound) => sound.id === 'music.parlour')).toBe(false);
  });
});
